name: Deploy to Linode on merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy USGS Exporter
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            /opt/deploy/usgs-exporter/vermilion.sh
